version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: tfg-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_DB_URL=http://localhost:3000/api/
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: tfg-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/TFG_DGB?authSource=admin
      - JWT_SECRET=dgb2005
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: tfg-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --auth

  mongo-express:
    image: mongo-express:latest
    container_name: tfg-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    container_name: tfg-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data: