[phases.setup]
nixPkgs = ['nodejs', 'npm', 'bash']

[phases.install]
cmds = [
    "bash -c 'cd frontend && npm install'",
    "bash -c 'cd backend && npm install'"
]

[phases.build]
cmds = [
    "bash -c 'cd frontend && npm run build'",
    "bash -c 'cd backend && npm install --only=production'"
]

[start]
cmd = "bash -c 'cd backend && npm start'"

[env]
NODE_ENV = "production"
PORT = "3000"